#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * Require composer autoload file. Not having this file means Composer might not be installed / run
 */
if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    die("ERROR :: File `".__DIR__."/vendor/autoload.php` not found. This indicate that composer has not yet been run on this install. Install composer and run `composer install` from the project root directory. Check the documentation for more details.\n");
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

\UF5Demo\App::main('cli');
